Controllers/CSOsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using hirelonghorn.DAL;
using hirelonghorn.Models;

namespace hirelonghorn.Controllers
{
    [Authorize]
    public class CSOsController : Controller
    {
        private readonly AppDbContext _context;

        public CSOsController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "CSO")]
        public IActionResult Index()
        {
            List<AppUser> CSOs = _context.Users.Where(c => c.Company == null && c.Major == null).ToList();
            return View(CSOs);
        }
    }
}

Controllers/RecruitersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using hirelonghorn.DAL;
using hirelonghorn.Models;

namespace hirelonghorn.Controllers
{
    [Authorize(Roles = "CSO")]
    public class RecruitersController : Controller
    {
        private readonly AppDbContext _context;

        public RecruitersController(AppDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            List<AppUser> recruiters = _context.Users.Where(r => r.Company != null).Include(r => r.Company).ToList();
            return View(recruiters);
        }
    }
}

Views/Shared/No48.cshtml

@{
    ViewData["Title"] = "No48";
}

<h2>The interviews should take place at least 48 hours after the application deadline for the position!</h2>

<div>
    <a asp-action="Index" asp-controller="Home">Back to Home Page</a>
</div>


Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Team 18</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nav-content">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Positions", "Index", "Positions", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Companies", "Index", "Companies", null, new { @class = "nav-link" })
                        </li>

                        if (User.IsInRole("Recruiter"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Students", "Index", "StudentSearch", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Interviews", "Index", "Interviews", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("UnScheduled Interviews", "Unbooked", "Interviews", null, new { @class = "nav-link" })
                            </li>
                        }

                        if (User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Interviews", "Index", "Interviews", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("UnScheduled Interviews", "Unbooked", "Interviews", null, new { @class = "nav-link" })
                            </li>
                        }

                        if (User.IsInRole("CSO"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Students", "Index", "StudentSearch", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Applications", "Index", "Applications", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Interviews", "Index", "Interviews", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("UnScheduled Interviews", "Unbooked", "Interviews", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Majors", "Index", "Majors", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Recruiter Profiles", "Index", "Recruiters", null, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("CSO Profiles", "Index", "CSOs", null, new { @class = "nav-link" })
                            </li>
                        }

                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Log In", "Index", "Account", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
            @await Html.PartialAsync("_LoginPartial")
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BevoSoft Consultants</p>
        </footer>
    </div>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/popper.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
</body>
</html>