Models/Position.cs
using hirelonghorn.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace hirelonghorn.Models
{
    public class Position
    {
        public Int32 PositionID { get; set; }

        [Required(ErrorMessage = "Position title is required")]
        [Display(Name = "Position Title")]
        public String PositionTitle { get; set; }

        [Display(Name = "Description")]
        public String Description { get; set; }

        [Required(ErrorMessage = "Position type is required")]
        [Display(Name = "Position Type")]
        public String PositionType { get; set; }

        [Required(ErrorMessage = "Location is required")]
        [Display(Name = "Location")]
        public String Location { get; set; }

        [Required(ErrorMessage = "Deadline is required")]
        [Display(Name = "Deadline")]
        [DataType(DataType.Date)]
        public DateTime Deadline { get; set; }

        public List <MajorPosition> MajorPositions { get; set; }

        public List<Application> Applications { get; set; }

        public List <Interview> Interviews { get; set; }

        public Company Company { get; set; }
    }
}

Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hirelonghorn.DAL;
using hirelonghorn.Models;

namespace hirelonghorn.Controllers
{   

    public enum Classification { ALL, FT, I }
    [Authorize]

    public class PositionsController : Controller
    {
        private readonly AppDbContext _context;

        public PositionsController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Positions
        public IActionResult Index()
        {
            if (User.IsInRole("CSO"))
            {
                ViewBag.AllPositionCount = _context.Positions.Count();
                ViewBag.SelectedPositionCount = _context.Positions.Count();

                var query = from p in _context.Positions
                            select p;

                return View(_context.Positions.Include(p => p.Company).ToList());
            }
            
            if (User.IsInRole("Recruiter"))
            {
                AppUser recruiter = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                List<Position> Positions = _context.Positions.Where(p => p.Company.AppUsers.Any(a=>a.Id == recruiter.Id ))
                    .Include(p => p.Company).ToList();
                return View(Positions);
            }
            

            else //(User.IsInRole("Student"))
            {
                ViewBag.AllPositionCount = _context.Positions.Where(p => p.Deadline >= Utilities.Time.SystemTime).Count();
                ViewBag.SelectedPositionCount = _context.Positions.Where(p => p.Deadline >= Utilities.Time.SystemTime).Count();

                var query = from p in _context.Positions
                            .Where(p => p.Deadline >= Utilities.Time.SystemTime)
                            select p;

                return View( _context.Positions.Where(p => p.Deadline >= Utilities.Time.SystemTime).Include(p => p.Company).ToList());
            }
        }

        [Authorize]
        // GET: Positions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Position position = await _context.Positions
                .Include(p => p.Company)
                .Include(p => p.MajorPositions).ThenInclude(m => m.Major)
                .Include(p=>p.Interviews)
                .FirstOrDefaultAsync(p => p.PositionID == id);
            if (position == null)
            {
                return NotFound();
            }
            return View(position);
        }

        [Authorize(Roles = "Recruiter, CSO")]
        public IActionResult Create()
        {
            Position pos = new Position();
            Company com = _context.Companies.FirstOrDefault(c => c.AppUsers.Any(a => a.UserName == User.Identity.Name));
            pos.Company = com;
            ViewBag.AllMajors = GetMajors();
            
            return View(pos);
        }

        [Authorize(Roles = "Recruiter, CSO")]
        public IActionResult CreateForACompany(int? id)
        {
            Position pos = new Position();
            Company com = _context.Companies.FirstOrDefault(c => c.CompanyID == id);
            pos.Company = com;
            ViewBag.AllMajors = GetMajors();

            return View(pos);
        }

        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Recruiter, CSO")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateForACompany([Bind("PositionID,PositionTitle,Description,PositionType,Location,Deadline,Company")] Position position, int[] SelectedMajors)
        {
            position.Company = _context.Companies.Find(position.Company.CompanyID);
            if (ModelState.IsValid)
            {
                _context.Add(position);
                _context.SaveChanges();

                Position dbPosition = _context.Positions
                    .Include(p => p.Company)
                    .FirstOrDefault(p => p.PositionID == position.PositionID);

                foreach (int m in SelectedMajors)
                {
                    //find the department specified by the int
                    Major maj = _context.Majors.Find(m);

                    //create a new instance of the bridge table class
                    MajorPosition cd = new MajorPosition();
                    cd.Position = dbPosition;
                    cd.Major = maj;

                    //add the new record to the database
                    _context.MajorPositions.Add(cd);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.AllMajors = GetAllMajors();
            return View(position);
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Recruiter, CSO")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PositionID,PositionTitle,Description,PositionType,Location,Deadline,Company")] Position position, int[] SelectedMajors)
        {
            position.Company = _context.Companies.Find(position.Company.CompanyID);
            if (ModelState.IsValid)
            {
                _context.Add(position);
                _context.SaveChanges();

                Position dbPosition = _context.Positions
                    .Include(p => p.Company)
                    .FirstOrDefault(p => p.PositionID == position.PositionID);
     
                foreach (int m in SelectedMajors)
                {
                    //find the department specified by the int
                    Major maj = _context.Majors.Find(m);

                    //create a new instance of the bridge table class
                    MajorPosition cd = new MajorPosition();
                    cd.Position = dbPosition;
                    cd.Major = maj;

                    //add the new record to the database
                    _context.MajorPositions.Add(cd);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.AllMajors = GetAllMajors();
            return View(position);
        }


        // GET: Positions/Edit/5
        [Authorize(Roles = "CSO, Recruiter")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Position position = await _context.Positions.FindAsync(id);
            if (position == null)
            {
                return NotFound();
            }

            ViewBag.AllMajors = GetAllMajors(position.PositionID);
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "CSO, Recruiter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PositionID,PositionTitle,Description,PositionType,Location,Deadline")] Position position, Classification SelectedClass, int[] SelectedMajors)
        {
            if (ModelState.IsValid)
            {
                Position dbPosition = _context.Positions
                   .Include(cd => cd.MajorPositions).ThenInclude(cd => cd.Major)
                   .FirstOrDefault(p => p.PositionID == position.PositionID);

                //create a list of departments to remove
                List<MajorPosition> MajorsToRemove = new List<MajorPosition>();

                //find departments that should no longer be there
                foreach (MajorPosition cd in dbPosition.MajorPositions)
                {
                    if (SelectedMajors.Contains(cd.Major.MajorID) == false)  //this department is not on the new list
                    {
                        MajorsToRemove.Add(cd);
                    }
                }

                //remove departments you found in the list above - this has to be 2 separate steps because you can't 
                //iterate over a list you are removing things from
                foreach (MajorPosition cd in MajorsToRemove)
                {
                    _context.MajorPositions.Remove(cd);
                    _context.SaveChanges();
                }

                //add departments that aren't already there
                foreach (int i in SelectedMajors)
                {
                    if (dbPosition.MajorPositions.Any(m => m.Major.MajorID == i) == false) //department is not already connect to this course
                    {
                        //create a new instance of the bridge table class
                        MajorPosition cd = new MajorPosition();
                        cd.Major = _context.Majors.Find(i);
                        cd.Position = dbPosition;

                        //add the new instance to the database
                        _context.MajorPositions.Add(cd);
                        _context.SaveChanges();
                    }
                }

                //update the scalar properties

Views/Positions/Create.cshtml
@model hirelonghorn.Models.Position

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.Company.CompanyName)
            @Html.HiddenFor(model => model.Company.CompanyEmail)
            @Html.HiddenFor(model => model.Company.CompanyID)
            @Html.HiddenFor(model => model.Company.Industry)
            @Html.HiddenFor(model => model.Company.Description)
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Position Type:</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.I)Intern</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.FT)Full Time</label>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Applicable Majors:</label>
                @Html.ListBox("SelectedMajors", (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Positions/CreateForACompany.cshtml
@model hirelonghorn.Models.Position

@{
    ViewData["Title"] = "Create For A Company";
}

<h2>Create</h2>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.Company.CompanyName)
            @Html.HiddenFor(model => model.Company.CompanyEmail)
            @Html.HiddenFor(model => model.Company.CompanyID)
            @Html.HiddenFor(model => model.Company.Industry)
            @Html.HiddenFor(model => model.Company.Description)
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Position Type:</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.I)Intern</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.FT)Full Time</label>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Applicable Majors:</label>
                @Html.ListBox("SelectedMajors", (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Positions/Delete.cshtml
@model hirelonghorn.Models.Position

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PositionTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PositionTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PositionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PositionType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PositionID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Positions/Details.cshtml
@model hirelonghorn.Models.Position

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Position</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PositionTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PositionTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PositionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PositionType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company.Industry)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.Industry)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>
    </dl>
</div>
<h5>Applicable Majors for this Position</h5>
<table class="table table-bordered">
    <tr>
        <th>Major Name</th>
    </tr>
    @foreach (MajorPosition cd in Model.MajorPositions)
    {
        <tr>
            <td>@cd.Major.MajorName</td>
        </tr>

    }
</table>
@if (User.IsInRole("CSO") || User.IsInRole("Recruiter"))
{
    <h5>Applicable Interview Date for Each Position</h5>
    <table class="table table-bordered">
        <tr>
            <th>Interview Date</th>
        </tr>
        @foreach (Interview cd in Model.Interviews)
        {
            <tr>
                <td>@cd.InterviewTime</td>
            </tr>

        }
    </table>
}


<div>

    @if (User.IsInRole("CSO") || User.IsInRole("Recruiter"))
    {
        <p>
            <a asp-action="Edit" asp-route-id="@Model.PositionID">Edit</a> |
        </p>
    }

    @if (User.IsInRole("Student"))
    {
        <p>
            <a asp-action="Apply" asp-route-id="@Model.PositionID">Apply</a> |
        </p>
    }

    <a asp-action="Index">Back to List</a>
</div>

Views/Positions/Edit.cshtml
@model hirelonghorn.Models.Position

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PositionID" />
            <div class="form-group">
                <label asp-for="PositionTitle" class="control-label"></label>
                <input asp-for="PositionTitle" class="form-control" />
                <span asp-validation-for="PositionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Position Type:</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.I)Intern</label>
                <label class="radio">@Html.RadioButton("PositionType", hirelonghorn.Controllers.Classification.FT)Full Time</label>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Applicable Majors:</label>
                @Html.ListBox("SelectedMajors", (MultiSelectList)ViewBag.AllMajors, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Positions/Index.cshtml
@model IEnumerable<hirelonghorn.Models.Position>

@{
    ViewData["Title"] = "Index";
}

<h2>Available Positions</h2>
@if (User.IsInRole("CSO") || User.IsInRole("Student"))
{
    <p class="form-group">
        <a asp-action="JobSearch" class="btn btn-danger">Search Job</a>
    </p>
    <p>
        Displaying @ViewBag.SelectedPositionCount of @ViewBag.AllPositionCount Positions
    </p>
}

@if (User.IsInRole("Recruiter"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PositionTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PositionType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.Industry)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PositionType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Deadline)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.Industry)
                </td>
                <td>

                    <a asp-action="Details" asp-route-id="@item.PositionID">Details</a> |

                </td>
            </tr>
        }
    </tbody>
</table>

Views/Positions/JobSearch.cshtml
@{
    ViewData["Title"] = "JobSearch";
}

<h2>Job Search</h2>
<form asp-action="DisplaySearchResults" asp-controller="Positions" method="get">
    <div class="form-group">
        <label>Search Position Title:</label>
        <input name="PositionTitle" class="form-control" />
    </div>

    <div class="form-group">
        <label>Search Position Description:</label>
        <input name="PositionDescription" class="form-control" />
    </div>

    <div class="form-group">
        <label class="radio">@Html.RadioButton("SelectedPosition", hirelonghorn.Controllers.Classification.ALL, true)All</label>
        <label class="radio">@Html.RadioButton("SelectedPosition", hirelonghorn.Controllers.Classification.FT)Full Time</label>
        <label class="radio">@Html.RadioButton("SelectedPosition", hirelonghorn.Controllers.Classification.I)Intern</label>
    </div>

    <div class="form-group">
        <label>Search Company Name:</label>
        <input name="Company" class="form-control" />
    </div>

    <div class="form-group">
        <label>Search Industry:</label>
        <input name="Industry" class="form-control" />
    </div>

    <div class="form-group">
        <label>Search Location:</label>
        <input name="Location" class="form-control" />
    </div>

    <div class="form-group">
        <label>Select a Major:</label>
        @Html.DropDownList("Major", (SelectList)ViewBag.AllMajors, new { @class = "form-control" })
    </div>
    

    <button type="submit" class="btn btn-danger">Search</button>
</form>
